/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni */

#ifndef _Included_Jni
#define _Included_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jni
 * Method:    jni_test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Jni_jni_1test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
